name: PR Integration Test for Repo2

on:
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run Tests
        run: python -m unittest discover

      # Build Docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/test-repo2:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/test-repo2:latest

        # Trigger Kube-Test Pipeline
      - name: Trigger Kube-Test Pipeline
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.KUBE_TEST_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/rlghks-aiofarm/kube-test/dispatches \
          -d '{"event_type": "pr-integration-test", "client_payload": {"updated_repo": "test-repo2"}}'

          echo "Kube-Test triggered, checking status..."

      # Check the status of Kube-Test Pipeline
      - name: Check Kube-Test Pipeline status
        run: |
          status_check_url="https://api.github.com/repos/rlghks-aiofarm/kube-test/actions/runs/${{ steps.kube_test_trigger.outputs.run_id }}/status"
          status_response=$(curl -H "Authorization: token ${{ secrets.KUBE_TEST_TOKEN }}" $status_check_url)

          # Check if the status is success
          if [[ "$status_response" != *"\"status\": \"success\""* ]]; then
            echo "Kube-Test failed. Exiting workflow."
            exit 1
          else
            echo "Kube-Test passed successfully."
          fi
      # # Deploy to Kubernetes
      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v3
      #   with:
      #     version: 'v1.26.0'

      # - name: Deploy to Kubernetes
      #   env:
      #     KUBECONFIG: ${{ secrets.KUBECONFIG }}
      #   run: |
      #     kubectl apply -f k8s/repo2-deployment.yaml
      #     kubectl apply -f k8s/repo2-service.yaml
